- https://en.wikipedia.org/wiki/Low-rank_approximation

$$
\begin{split}
&A_{m\times n}=U_{m\times m}\Sigma_{m\times n} V^T_{n\times n}\\
&A_k=\sum_{i=1}^k\sigma_iu_iv_i^T
\end{split}
$$

## $U,\Sigma, V^T$ 的性质补充

In [1]:
import numpy as np

In [25]:
A = np.random.randn(3, 5)
A

array([[-0.3866689 ,  0.33928507,  0.10520867, -0.03458687, -0.31500214],
       [-0.97880869,  0.44260941,  2.96062902,  2.0931785 , -0.25936143],
       [ 0.4713509 , -0.73204923, -0.6700932 , -1.42363598, -0.31543659]])

### 分解及还原

In [26]:
U, s, Vt = np.linalg.svd(A)

In [27]:
U

array([[ 0.0558686 , -0.00895655,  0.99839796],
       [ 0.91986024, -0.38837711, -0.05495786],
       [-0.38824715, -0.921457  ,  0.01345931]])

In [28]:
# 1d vector
# 降序排列的
s

array([4.10019424, 0.97015882, 0.56974413])

In [29]:
Vt

array([[-0.26949223,  0.17323818,  0.72908852,  0.60392796, -0.03261007],
       [-0.05227956,  0.51498136, -0.54972523,  0.51454101,  0.40633824],
       [-0.57203248,  0.53456237, -0.11705028, -0.29614914, -0.53443131],
       [ 0.75872269,  0.56237125,  0.19825893, -0.07565604, -0.25109364],
       [-0.14751105,  0.32056883,  0.33648882, -0.52639378,  0.69653498]])

In [30]:
S = np.zeros_like(A)
S[:3, :3] = np.diag(s)
A_rec = U.dot(S).dot(Vt)
A_rec

array([[-0.3866689 ,  0.33928507,  0.10520867, -0.03458687, -0.31500214],
       [-0.97880869,  0.44260941,  2.96062902,  2.0931785 , -0.25936143],
       [ 0.4713509 , -0.73204923, -0.6700932 , -1.42363598, -0.31543659]])

In [31]:
np.allclose(A_rec, A)

True

### 性质补充

- $U_{m\times n}$ 是 $AA^T$ 的特征向量组成
- $\Sigma_{m\times n}$是 $A^TA$ 的特征值的根号形式
- $V^T_{n\times n}$ 是 $A^TA$ 的特征向量组成

In [32]:
U

array([[ 0.0558686 , -0.00895655,  0.99839796],
       [ 0.91986024, -0.38837711, -0.05495786],
       [-0.38824715, -0.921457  ,  0.01345931]])

In [33]:
np.linalg.eig(A.dot(A.T))

(array([16.8115928 ,  0.32460838,  0.94120814]),
 array([[ 0.0558686 ,  0.99839796,  0.00895655],
        [ 0.91986024, -0.05495786,  0.38837711],
        [-0.38824715,  0.01345931,  0.921457  ]]))

In [34]:
s**2

array([16.8115928 ,  0.94120814,  0.32460838])

In [37]:
np.linalg.eig(A.T.dot(A))

(array([ 1.68115928e+01,  9.41208139e-01,  3.24608379e-01, -1.75815656e-16,
        -9.86791092e-16]),
 array([[ 0.26949223, -0.05227956, -0.57203248, -0.0619002 ,  0.38078615],
        [-0.17323818,  0.51498136,  0.53456237,  0.38133775,  0.60905971],
        [-0.72908852, -0.54972523, -0.11705028,  0.35651584,  0.38460647],
        [-0.60392796,  0.51454101, -0.29614914, -0.53154906, -0.44932162],
        [ 0.03261007,  0.40633824, -0.53443131,  0.66415505,  0.36638249]]))

In [38]:
Vt

array([[-0.26949223,  0.17323818,  0.72908852,  0.60392796, -0.03261007],
       [-0.05227956,  0.51498136, -0.54972523,  0.51454101,  0.40633824],
       [-0.57203248,  0.53456237, -0.11705028, -0.29614914, -0.53443131],
       [ 0.75872269,  0.56237125,  0.19825893, -0.07565604, -0.25109364],
       [-0.14751105,  0.32056883,  0.33648882, -0.52639378,  0.69653498]])

## 低秩逼近（low rank approximation）

- https://en.wikipedia.org/wiki/Low-rank_approximation

$$
\begin{split}
&A_{m\times n}=U_{m\times m}\Sigma_{m\times n} V^T_{n\times n}\\
&A_k=\sum_{i=1}^k\sigma_iu_iv_i^T
\end{split}
$$

In [17]:
def low_rank_k(U, S, Vt, k):
    m, n = U.shape[0], Vt.shape[0]
    A_k = np.zeros((m, n))
    for i in range(k):
        A_k += S[i]*U[:, [i]].dot(Vt[[i], :])
    return A_k

In [40]:
print(A)
print(np.linalg.matrix_rank(A))

[[-0.3866689   0.33928507  0.10520867 -0.03458687 -0.31500214]
 [-0.97880869  0.44260941  2.96062902  2.0931785  -0.25936143]
 [ 0.4713509  -0.73204923 -0.6700932  -1.42363598 -0.31543659]]
3


In [41]:
print(low_rank_k(U, s, Vt, 1))
np.linalg.matrix_rank(low_rank_k(U, s, Vt, 1))

[[-0.06173315  0.03968403  0.16701383  0.13834304 -0.00747006]
 [-1.01641841  0.65338611  2.74983437  2.27777811 -0.12299234]
 [ 0.42900164 -0.27577591 -1.16062779 -0.96138611  0.05191161]]


1

In [42]:
print(low_rank_k(U, s, Vt, 2))
np.linalg.matrix_rank(low_rank_k(U, s, Vt, 2))

[[-0.06127888  0.03520922  0.17179054  0.13387206 -0.01100084]
 [-0.99672013  0.45934758  2.95696396  2.0839055  -0.2760955 ]
 [ 0.47573746 -0.73614845 -0.66919562 -1.421365   -0.31133838]]


2

In [43]:
print(low_rank_k(U, s, Vt, 3))
np.linalg.matrix_rank(low_rank_k(U, s, Vt, 3))

[[-0.3866689   0.33928507  0.10520867 -0.03458687 -0.31500214]
 [-0.97880869  0.44260941  2.96062902  2.0931785  -0.25936143]
 [ 0.4713509  -0.73204923 -0.6700932  -1.42363598 -0.31543659]]


3

In [44]:
A

array([[-0.3866689 ,  0.33928507,  0.10520867, -0.03458687, -0.31500214],
       [-0.97880869,  0.44260941,  2.96062902,  2.0931785 , -0.25936143],
       [ 0.4713509 , -0.73204923, -0.6700932 , -1.42363598, -0.31543659]])